# Generated by Django 4.2.19 on 2025-05-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preffered_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=100, verbose_name='Preffered Language')),
                ('referrer', models.CharField(choices=[('ln', 'Linkedin'), ('fb', 'Facebook'), ('yt', 'Youtube'), ('in', 'Instagram'), ('tk', 'TikTok'), ('pn', 'personal Network'), ('pfn', 'Professional Network'), ('ot', 'Other Network')], max_length=50, verbose_name='How did you hear about the platfrom?')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
