# Generated by Django 4.2.19 on 2025-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl_extra_reg_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='preffered_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=100, verbose_name='Preferred Language'),
        ),
    ]
