# Generated by Django 4.2.19 on 2025-05-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl_extra_reg_fields', '0002_alter_extrainfo_preffered_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='preffered_language',
            new_name='preferred_language',
        ),
    ]
